version: "3.1"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php:
    build:
      context: .
    ports:
      - 8081:80
    volumes:
      - .:/var/www/
