<?php

/**
 * MyStudent API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class PeopleApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation listPeople
     *
     * List people data.
     *
     *
     * @return Http response
     */
    public function listPeople(Request $request)
    {
        $input = $request->all();

        //path params validation


        //not path params validation

        return response('How about implementing listPeople as a get method ?');
    }
}
